# Generated by Django 5.2 on 2025-04-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question1_choice1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice1',
        ),
        migrations.DeleteModel(
            name='Question1',
        ),
    ]
