# Generated by Django 5.2 on 2025-04-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_choice1_delete_question1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sister_name',
            name='last_name',
        ),
        migrations.DeleteModel(
            name='myname',
        ),
        migrations.DeleteModel(
            name='sister_name',
        ),
    ]
