# Generated by Django 5.2 on 2025-04-06 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='img',
            field=models.ImageField(default=None, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
